project:
  type: website
  output-dir: "."

website:
  title: "Jeremy Sun"
  navbar:
    pinned: true #first level indention
    left:
      - text: Project #second level indention 
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      -  text: Classwork
         href: danlCW10.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
